image: Visual Studio 2017
configuration: Release
before_build:
  - cmd: nuget restore
after_build:
  - cmd: 7z a myapp.zip %APPVEYOR_BUILD_FOLDER%\com.aboersch.PostProxy.Function\bin\Release\net461\*
artifacts:
  - path: myapp.zip
    name: app
deploy:
  - provider: WebDeploy
    server: https://post-proxy.scm.azurewebsites.net:443/msdeploy.axd?site=post-proxy
    website: post-proxy
    username: $post-proxy
    password:
      secure: okYCVNEge95NfxAbCE4OUiKVQ9k0eQ8XhGQ+mvr6r+DOkw0AnpZ9x+9kjAMurUarObHohhjPmkMnJDuP2bOzrQ==
    remove_files: false
    app_offline: false
    ntlm: false
    artifact: app
after_deploy:
  - ps: |
      $baseUrl = "https://post-proxy.azurewebsites.net/api"
      $escapedTestPostUrl = [Uri]::EscapeDataString("$baseUrl/TestPost")
      $testUrl = "$baseUrl/PostProxy?url=$escapedTestPostUrl&name=Test"
      $webRequest = Invoke-WebRequest -Uri "$testurl"
      if(!$webRequest.Content.Equals('"Hello Test"'))
      { 
        throw "Smoke Test Failed"
      }
