image: Visual Studio 2017
configuration: Release
before_build:
  - cmd: nuget restore
artifacts:
  - path: com.aboersch.PostProxy\bin\$(configuration)\**\*.*
    name: app
deploy:
  - provider: FTP
    host: waws-prod-am2-123.ftp.azurewebsites.windows.net/site/wwwroot
    protocol: ftp
    username: post-proxy\$post-proxy
    password:
      secure: Y+DtdyBvdsOrb+ZKMr8bJ+xUvkTu+kmljQ0fqmSuC/r9HaeJLxn0AzN6fL8zLcgtDZ7fm0c+leNE964py9bCwQ==
after_deploy:
  - ps: >
    $baseUrl = "https://post-proxy.azurewebsites.net/api"
    $escapedTestPostUrl = [Uri]::EscapeDataString("$baseUrl/TestPost")
    $testUrl = "$baseUrl/PostProxy?url=$escapedTestPostUrl&name=Test"
    $webRequest = Invoke-WebRequest -Uri "$testurl"
    if(!$webRequest.Content.Equals('"\"Hello FAIL\""'))
    { 
      throw "Smoke Test Failed"
    }