image: Visual Studio 2017
configuration: Release
before_build:
  - cmd: nuget restore
after_build:
  - ps: |
      $folderPath = "$($env:APPVEYOR_BUILD_FOLDER)\com.aboersch.PostProxy\bin\Release\net461"
      Write-Host $folderPath
      $folder = Get-Item $folderPath
      $folder.GetDirectories() | % { Move-Item $_.FullName $folder.Parent.FullName }
      Rename-Item $folderPath bin
      Compress-Archive ([IO.Path]::Combine($folder.Parent.FullName, "bin")) myapp.zip
artifacts:
  - path: myapp.zip
    name: app
deploy:
  - provider: WebDeploy
    server: https://post-proxy.scm.azurewebsites.net:443/msdeploy.axd?site=post-proxy
    website: post-proxy
    username: $post-proxy
    password:
      secure: Y+DtdyBvdsOrb+ZKMr8bJ+xUvkTu+kmljQ0fqmSuC/r9HaeJLxn0AzN6fL8zLcgtDZ7fm0c+leNE964py9bCwQ==
    remove_files: false
    app_offline: false
    ntlm: false
    artifact: app
after_deploy:
  - ps: |
      $baseUrl = "https://post-proxy.azurewebsites.net/api"
      $escapedTestPostUrl = [Uri]::EscapeDataString("$baseUrl/TestPost")
      $testUrl = "$baseUrl/PostProxy?url=$escapedTestPostUrl&name=Test"
      $webRequest = Invoke-WebRequest -Uri "$testurl"
      if(!$webRequest.Content.Equals('"\"Hello Test\""'))
      { 
        throw "Smoke Test Failed"
      }
